spring:

  config:
    import: optional:file:.env

  jackson:
    deserialization:
      fail-on-unknown-properties: false

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${DEFAULT.DB_URL}
    username: ${DEFAULT.DB_USERNAME}
    password: ${DEFAULT.DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB

  security:
    user:
      name: root
      password: 1111

  profiles:
    active: dev

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
  cache:
    disabled: true

file:
  directory: ${DEFAULT.FILE_DIRECTORY}

# custom 속성 지정
app:
  jwt:
    # JWT 만들 때 사용하는 열쇠(암호화) > 나중에 복호화 할때도 사용
    secret: ${JWT_SECRET}

    #front-back 간 JWT받는 헤더 키 이름
    header-schema-name: authorization

    #토큰의 종류: Bearer 는 JWT or OAuth(소셜로그인 때 사용)를 의미
    token-type: Bearer

    #AT - 만료시간(ms) - 30분
    access-token-expiry: 1_800_000

    #RT - 만료시간(ms) - 15일
    refresh-token-expiry: 1_296_000_000

management:
  endpoints:
    web:
      exposure:
        include: "*" # actuator 의 모든 EndPoint 를 웹에 노출
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080  # localhost:8080 에서 접근할 때만 볼 수 있도록 한다 -> Docker 에 올리면 접근이 불가능하다.